baseURL = 'https://selcukbayram.github.io/'
locale = 'tr-TR'
title = 'Selçuk Bayram'
theme = 'PaperMod'

[params]
  env = "production"
  title = "Selçuk Bayram"
  description = "Metin1 | Metin2"
  keywords = ["Blog", "Portfolyo", "Embedded Systems", "Selçuk Bayram"]
  author = "Selçuk Bayram"
  showToc = true
  TocOpen = false
  hidemeta = false
  comments = false
  disableShare = false
  disableHLJS = false
  showReadingTime = true
  showBreadCrumbs = true
  showPostNavLinks = true
  showWordCount = true
  useHugoFavicon = true

  [params.profileMode]
    enabled = true
    title = "Selçuk Bayram"
    subtitle = ""
    imageUrl = "profil-fotografı.jpg"
    imageWidth = 120
    imageHeight = 120


  [[params.profileMode.buttons]]
    name = "Hakkımda"
    url = "/hakkımda/"

  [[params.profileMode.buttons]]
    name = "Projeler"
    url = "/projeler/"

  [[params.profileMode.buttons]]
    name = "Blog"
    url = "/posts/"

  [[params.profileMode.buttons]]
    name = "İletişim"
    url = "#"

  [[params.profileMode.buttons]]
    name = "Gallery"
    url = "/gallery"

  [[params.profileMode.buttons]]
    name = "Cv"
    url = "/cv/"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/selcukbayram0"

  [[params.socialIcons]]
    name = "GitHub"
    url = "https://github.com/selcukbayram"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github-dark"